### ISSUE TITLE
Support/FIX for PHPIPAM 1.6

### ISSUE THREAD

**Issue by lord-kyron** [lord-kyron/terraform-provider-phpipam#79]
Hi @pavel-z1 ,
Since I tried to use PHPIPAM 1.6 as per some requirements, it seems that the login is now broken.
I am getting this error:
`HTTP/1.1 415 Unsupported Media Type`

It seems related to me to this issue, as I've tested with CURL and I am getting the same results as described here:
https://github.com/phpipam/phpipam/issues/1976
NOT working: `curl -X POST --user apiuser:test1234 http://localhost/api/testapp/user/ -i`
Working: `curl -X POST -H "Content-Type: application/json" --user apiuser:test1234 http://localhost/api/testapp/user/ -i`

Maybe there is something that needs to be added to the headers of the current request to support it.
I can see that this issue is an old one, but suddenly after the upgrade we started receiving this error.
Please, check it when you can and elaborate!
Thanks!

**Comment by pavel-z1** [comment]
Hi @lord-kyron 
I correctly understood that the problem was solved? What caused it?

**Comment by lord-kyron** [comment]
It seems PHPIPAM 1.6 is still not fully compatible with PHP 8.1 and we tried to use PHP 8.1
After we reverted to PHP 7.4 it is back to normal.
